{
 "title": "** Overview v0.2**",
 "description": "색상 및 패널 수정 250225",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "구독",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: flex-end; height: 100%; color: #000000; font-size: 20px; flex-direction: column; text-align: left; width: 100%;\">\n    <span style=\"font-weight: bold;\">${__from:date:YYYY-MM} COST</span>\n</div>\n"
   }
  },
  {
   "title": "${Subscription}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "repeat": "Subscription",
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT LAST(\"total_cost\") FROM \"monthly_cost\" WHERE (\"subscription_id\"::tag = '$Subscription') AND time > now() - 24h"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 45 }
   ]
  },
  {
   "title": "구독별 월 비용",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "monthly_cost",
     "query": "SELECT \"subscription_id\", \"total_cost\" FROM \"monthly_cost\" WHERE (\"subscription_id\"::tag = '4b0a5f96-43b7-4e90-9dc7-223cfa72c86b' OR \"subscription_id\"::tag = '5fbbb1e7-7f66-4904-ba32-dbf0a40f224f' OR \"subscription_id\"::tag = 'bcab936a-2388-454c-b309-1aca8620a15d' OR \"subscription_id\"::tag = 'ea01e5db-cabf-403f-9cc2-a6abf0d25f7b' OR \"subscription_id\"::tag = '5d98fd4c-bf45-4fe6-a554-68c369997297') AND time > now() - 24h",
     "select": [
      [
       { "params": [ "subscription_id" ], "type": "field" }
      ],
      [
       { "params": [ "total_cost" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "subscription_id::tag",
       "operator": "=",
       "value": "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
      },
      {
       "condition": "OR",
       "key": "subscription_id::tag",
       "operator": "=",
       "value": "5fbbb1e7-7f66-4904-ba32-dbf0a40f224f"
      },
      {
       "condition": "OR",
       "key": "subscription_id::tag",
       "operator": "=",
       "value": "bcab936a-2388-454c-b309-1aca8620a15d"
      },
      {
       "condition": "OR",
       "key": "subscription_id::tag",
       "operator": "=",
       "value": "ea01e5db-cabf-403f-9cc2-a6abf0d25f7b"
      }
     ]
    },
    {
     "azureResourceGraph": {
      "query": "resourcecontainers\r\n| where type == \"microsoft.resources/subscriptions\"\r\n| project subscriptionName = tostring(name), subscription_id = tostring(subscriptionId)"
     },
     "subscriptions": [
      "5d98fd4c-bf45-4fe6-a554-68c369997297",
      "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b",
      "bcab936a-2388-454c-b309-1aca8620a15d",
      "ea01e5db-cabf-403f-9cc2-a6abf0d25f7b",
      "5fbbb1e7-7f66-4904-ba32-dbf0a40f224f"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 16 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: flex-end; height: 100%; color: #000000; font-size: 20px; flex-direction: column; text-align: left; width: 100%;\">\n    <span style=\"font-weight: bold;\">COMPUTE</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 16 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: flex-end; height: 100%; color: #000000; font-size: 20px; flex-direction: column; text-align: left; width: 100%;\">\n    <span style=\"font-weight: bold;\">NETWORK</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 16 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: flex-end; height: 100%; color: #000000; font-size: 20px; flex-direction: column; text-align: left; width: 100%;\">\n    <span style=\"font-weight: bold;\">DATABASE</span>\n</div>\n\n"
   }
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "리소스 수량",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type =~ \"microsoft.compute/virtualmachines\" or type =~ \"microsoft.web/sites\" or type =~ \"microsoft.containerservice/managedclusters\"\r\n| project VM = countof(type,\"microsoft.compute/virtualmachines\"), Webapp = countof(type,\"microsoft.web/sites\"), AKS = countof(type,\"microsoft.containerservice/managedclusters\")"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 2, "y": 18 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; height: 100%; color: #000000; font-size: 15px; flex-direction: column; text-align: center; width: 100%; background-color: white;\">\n    <span style=\"font-weight: 500;\">Status</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 9, "y": 18 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; height: 100%; color: #000000; font-size: 13px; flex-direction: column; text-align: center; width: 100%; background-color: white;\">\n    <span style=\"font-weight: 700;\">부하 분산 장치</span>\n</div>\n"
   }
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "리소스 수량",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type in ( \r\n    \"microsoft.dbforpostgresql/servers\",\r\n    \"microsoft.dbforpostgresql/flexibleservers\",\r\n    \"microsoft.cache/redis\",\r\n    \"microsoft.documentdb/databaseaccounts\",\r\n    \"microsoft.dbformysql/servers\",\r\n    \"microsoft.dbformysql/flexibleservers\",\r\n    \"Microsoft.Sql/servers\")\r\n| summarize count() by type\r\n| order by type asc\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 18 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; height: 100%; color: #000000; font-size: 15px; flex-direction: column; text-align: center; width: 100%; background-color: white;\">\n    <span style=\"font-weight: 500;\">Status</span>\n</div>\n"
   }
  },
  {
   "title": "VM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type == \"microsoft.compute/virtualmachines\" // VM 리소스만 필터링\r\n| extend vmState = tostring(properties.extended.instanceView.powerState.code) // VM 상태 추출\r\n| where vmState == \"PowerState/running\" // 실행 중인 VM만 필터링\r\n| summarize runningVMs = count()\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    },
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type == \"microsoft.compute/virtualmachines\" // VM 리소스만 필터링\r\n| extend vmState = tostring(properties.extended.instanceView.powerState.code) // VM 상태 추출\r\n| where vmState == \"PowerState/deallocated\" // 중지된 VM만 필터링\r\n| summarize stoppedVMs = count()\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "WEB APP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type == \"microsoft.web/sites\" // Web App 리소스 필터링\r\n| extend deletionTime = todatetime(properties.deletionTimestamp) // 삭제 시간 추출\r\n| summarize \r\n    runningWebApps = countif(properties.state == \"Running\"), // 실행 중인 Web Apps 수\r\n    stoppedWebApps = countif(properties.state != \"Running\") // 중지된 Web Apps 수\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "AKS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type == \"microsoft.containerservice/managedclusters\"\r\n| extend powerState = tostring(properties.powerState.code)\r\n| summarize \r\n    runningAKSCount = countif(powerState == \"Running\"),\r\n    stoppedAKSCount = countif(powerState == \"Stopped\")\r\n| mv-expand state = pack_array(\"Running AKS\", \"Stopped AKS\"), \r\n                    value = pack_array(runningAKSCount, stoppedAKSCount)\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "LB Probe",
   "type": "stat",
   "description": "Load Balancer Probe",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "LB : {{resourcename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "DipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "region": "koreacentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/loadBalancers",
        "region": "koreacentral",
        "resourceGroup": "aks-node-RG",
        "resourceName": "kubernetes",
        "subscription": "bcab936a-2388-454c-b309-1aca8620a15d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "bcab936a-2388-454c-b309-1aca8620a15d"
    }
   ]
  },
  {
   "title": "AGW Backend Status",
   "type": "stat",
   "description": "Application Gateway 백엔드 응답 상태",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Healthy",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "koreacentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "koreacentral",
        "resourceGroup": "aks-node-RG",
        "resourceName": "applicationgateway",
        "subscription": "bcab936a-2388-454c-b309-1aca8620a15d"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "bcab936a-2388-454c-b309-1aca8620a15d"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Unhealthy",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UnhealthyHostCount",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "koreacentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "koreacentral",
        "resourceGroup": "aks-node-RG",
        "resourceName": "applicationgateway",
        "subscription": "bcab936a-2388-454c-b309-1aca8620a15d"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "bcab936a-2388-454c-b309-1aca8620a15d"
    }
   ]
  },
  {
   "title": "Cache for Redis",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type == \"microsoft.cache/redis\" // Redis Cache 리소스 필터링\r\n| extend cacheState = tostring(properties.provisioningState) // 캐시 상태 추출\r\n| where cacheState == \"Succeeded\" or cacheState == \"Stopped\" // 상태 필터링\r\n| project succeededRedisCaches = countof(cacheState,\"Succeeded\"), stoppedRedisCaches = countof(cacheState,\"stopped\")\r\n"
     },
     "subscriptions": [
      "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type in (\"microsoft.dbforpostgresql/servers\", \"microsoft.dbforpostgresql/flexibleservers\") // PostgreSQL 리소스 필터링\r\n| extend serverState = tostring(properties.state) // 서버 상태 추출\r\n| where serverState == \"Ready\" or serverState == \"Stopped\"\r\n| project readyPostgreSQLServers = countof(serverState,\"Ready\"), stoppedPostgreSQLServers= countof(serverState,\"Stopped\")\r\n"
     },
     "subscriptions": [
      "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
     ]
    }
   ]
  },
  {
   "title": "CosmosDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type == \"microsoft.documentdb/databaseaccounts\" // Cosmos DB 계정 리소스 필터링\r\n| extend accountState = tostring(properties.provisioningState) // 계정 상태 추출\r\n| where accountState == \"Succeeded\" or accountState == \"Stopped\" \r\n| project succeededAccounts = countof(accountState,\"Succeeded\"), stoppedAccounts = countof(accountState,\"stopped\")\r\n"
     },
     "subscriptions": [
      "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 2, "y": 23 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; height: 100%; color: #000000; font-size: 13px; flex-direction: column; text-align: center; width: 100%; background-color: white;\">\n    <span style=\"font-weight: 700;\">생성 / 삭제 (24시간)</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 9, "y": 23 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; height: 100%; color: #000000; font-size: 15px; flex-direction: column; text-align: center; width: 100%; background-color: white;\">\n    <span style=\"font-weight: 500;\">VPN</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 23 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: flex-end; height: 100%; color: #000000; font-size: 20px; flex-direction: column; text-align: left; width: 100%;\">\n    <span style=\"font-weight: bold;\"></span>\n</div>\n\n"
   }
  },
  {
   "title": "VM",
   "type": "stat",
   "description": "24시간 이내 생성 및 삭제된  VM 수",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type =~ \"Microsoft.Compute/virtualMachineScaleSets/virtualMachines\" // VMSS 내 VM 인스턴스 필터링\r\n| extend creationTime = todatetime(properties.timeCreated) // 생성 시간 추출\r\n| extend deletionTime = todatetime(properties.deletionTimestamp) // 삭제 시간 추출\r\n| summarize \r\n    createdVMCount = countif(creationTime > ago(24h)), // 최근 24시간 내 생성된 VM 수\r\n    deletedVMCount = countif(deletionTime > ago(24h)) // 최근 24시간 내 삭제된 VM 수\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "WEBAPP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type =~ \"Microsoft.Web/sites\" // Web App 리소스 필터링\r\n| extend creationTime = todatetime(properties.createdTime) // 생성 시간 추출\r\n| extend deletionTime = todatetime(properties.deletionTimestamp) // 삭제 시간 추출\r\n| summarize \r\n    createdWebAppCount = countif(creationTime > ago(24h)), // 최근 24시간 내 생성된 Web App 수\r\n    deletedWebAppCount = countif(deletionTime > ago(24h)) // 최근 24시간 내 삭제된 Web App 수\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "AKS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type =~ \"Microsoft.ContainerService/managedClusters\" // AKS 리소스 필터링\r\n| extend creationTime = todatetime(properties.createdTime) // 생성 시간 추출\r\n| extend deletionTime = todatetime(properties.deletionTimestamp) // 삭제 시간 추출\r\n| summarize \r\n    createdAKSCount = countif(creationTime > ago(24h)), // 최근 24시간 내 생성된 AKS 클러스터 수\r\n    deletedAKSCount = countif(deletionTime > ago(24h)) // 최근 24시간 내 삭제된 AKS 클러스터 수\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "S2S Status",
   "type": "stat",
   "description": "VPN S2S 연결 상태",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "resources\r\n| where type contains \"Microsoft.Network/connections\" and name =~ \"sy-vpn-ai-s2s\"\r\n| parse properties.virtualNetworkGateway1.id with * \"/Microsoft.Network/virtualNetworkGateways/\" VNG_Name\r\n| parse properties.localNetworkGateway2.id with * \"/Microsoft.Network/localNetworkGateways/\" LNG_Name\r\n| project name, Status=tostring(properties.connectionStatus)"
     },
     "subscriptions": [
      "bcab936a-2388-454c-b309-1aca8620a15d"
     ]
    }
   ]
  },
  {
   "title": "P2S Client ",
   "type": "stat",
   "description": "VPN P2S 사용자 수",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{resourcename}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "P2SConnectionCount",
      "metricNamespace": "microsoft.network/virtualnetworkgateways",
      "region": "koreacentral",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/virtualNetworkGateways",
        "region": "koreacentral",
        "resourceGroup": "sy-vpn-rg",
        "resourceName": "sy-vpn-ai-vng",
        "subscription": "bcab936a-2388-454c-b309-1aca8620a15d"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "bcab936a-2388-454c-b309-1aca8620a15d"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type in (\"microsoft.dbformysql/servers\", \"microsoft.dbformysql/flexibleservers\") // MySQL 리소스 필터링\r\n| extend serverState = tostring(properties.state) // 서버 상태 추출\r\n| where serverState == \"Ready\" or serverState == \"Stopped\" \r\n| project readyMySQLServers = countof(serverState,\"Ready\"), stoppedMySQLServers = countof(serverState,\"Stopped\")\r\n"
     },
     "subscriptions": [
      "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
     ]
    }
   ]
  },
  {
   "title": "MSSQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type =~ \"Microsoft.Sql/servers\" // Microsoft SQL 서버 리소스 필터링\r\n| extend serverState = tostring(properties.state) // 서버 상태 추출\r\n| where serverState == \"Ready\" or serverState == \"Stopped\" // 상태 필터링\r\n| project readySQLServers = countof(serverState,\"Ready\"), stoppedSQLServers = countof(serverState,\"Stoppped\")\r\n"
     },
     "subscriptions": [
      "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
     ]
    }
   ]
  },
  {
   "title": "MSSQL DB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| where type =~ \"Microsoft.Sql/servers/databases\" // Microsoft SQL 데이터베이스 리소스 필터링\r\n| extend databaseState = tostring(properties.status) // 데이터베이스 상태 추출\r\n| where databaseState == \"Online\" or  databaseState == \"Paused\"// 상태 필터링\r\n| project onlineDatabases = countof(databaseState, \"Online\"),  pausedDatabases = countof(databaseState, \"paused\")\r\n"
     },
     "subscriptions": [
      "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
     ]
    }
   ]
  }
 ]
}