{
 "title": "1. Subscription",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "구독",
    "query": {}
   },
   {
    "name": "subscription",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center; height: 100%; color: #000000; font-size: 30px; flex-direction: column; text-align: center; width: 100%;\">\n    <span style=\"font-weight: bold;;\">[ 비용 ]</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 14, "x": 10, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center; height: 100%; color: #000000; font-size: 30px; flex-direction: column; text-align: center; width: 100%;\">\n    <span style=\"font-weight: bold;\">[ 리소스 ]</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; align-items: center; height: 100%; color: #000000; font-size: 40px; flex-direction: column; text-align: center; width: 100%;\">\n    <span style=\"font-weight: bold;\">${__from:date:YYYY-MM} ver.</span>\n</div>\n"
   }
  },
  {
   "title": "월 비용",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "date::field" ], "type": "tag" }
     ],
     "measurement": "daily_cost",
     "query": "SELECT LAST(\"total_cost\") FROM \"monthly_cost\" WHERE (\"subscription_id\"::tag = '$Subscription') AND time > now() - 24h",
     "select": [
      [
       { "params": [ "total_cost" ], "type": "field" }
      ],
      [
       { "params": [ "date" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "subscription_id::tag",
       "operator": "=",
       "value": "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
      }
     ]
    }
   ]
  },
  {
   "title": "리소스 개요",
   "type": "stat",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "resourcecontainers\r\n| where type =~ \"microsoft.resources/subscriptions/resourcegroups\"\r\n| summarize resourcegroup = count()"
     },
     "subscriptions": [ "$Subscription" ]
    },
    {
     "azureResourceGraph": {
      "query": "Resources\r\n| summarize resource = count()"
     },
     "subscriptions": [ "$Subscription" ]
    },
    {
     "azureResourceGraph": {
      "query": "resourcechanges\r\n| where type == 'microsoft.resources/changes'\r\n| extend timestamp = todatetime(properties.changeAttributes.timestamp),\r\n    change_type = properties.changeType\r\n| where timestamp >= ago(24h) and change_type == \"Create\"\r\n| summarize create = count()"
     },
     "subscriptions": [ "$Subscription" ]
    },
    {
     "azureResourceGraph": {
      "query": "resourcechanges\r\n| where type == 'microsoft.resources/changes'\r\n| extend timestamp = todatetime(properties.changeAttributes.timestamp),\r\n    change_type = properties.changeType\r\n| where timestamp >= ago(24h) and change_type == \"Delete\"\r\n| summarize delete = count()"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "일별 비용",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "date::field" ], "type": "tag" }
     ],
     "measurement": "daily_cost",
     "query": "SELECT \"date\", \"total_cost\" FROM \"daily_cost\" WHERE (\"subscription_id\"::tag = '$Subscription') AND time > now() - 24h",
     "select": [
      [
       { "params": [ "total_cost" ], "type": "field" }
      ],
      [
       { "params": [ "date" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "subscription_id::tag",
       "operator": "=",
       "value": "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
      }
     ]
    }
   ]
  },
  {
   "title": "지역별 리소스 개수",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 7 },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "resources\r\n| summarize ResourceCount = count() by location\r\n| order by ResourceCount desc"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "유형별 리소스 개수",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "resources\r\n| summarize ResourceCount = count() by type\r\n| extend type = tostring(ResourceType = split(type, \"/\")[-1])\r\n| order by ResourceCount desc\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "리소스별 비용",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "date::field" ], "type": "tag" }
     ],
     "measurement": "daily_cost",
     "query": "SELECT \"service_name\", \"total_cost\" FROM \"service_cost\" WHERE (\"subscription_id\"::tag = '$Subscription') AND time > now() - 24h",
     "select": [
      [
       { "params": [ "total_cost" ], "type": "field" }
      ],
      [
       { "params": [ "date" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "subscription_id::tag",
       "operator": "=",
       "value": "4b0a5f96-43b7-4e90-9dc7-223cfa72c86b"
      }
     ]
    }
   ]
  },
  {
   "title": "리소스 삭제/생성 (24시간 이내)",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 19 },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "resourcechanges\r\n| where type == 'microsoft.resources/changes'\r\n| extend timestamp = todatetime(properties.changeAttributes.timestamp),\r\n    change_type = properties.changeType,\r\n    changed_by = properties.changeAttributes.changedBy,\r\n    resource = tostring(split(properties.targetResourceType, \"/\")[array_length(split(properties.targetResourceType, \"/\")) -1]),\r\n    resource_name = tostring(split(properties.targetResourceId, \"/\")[array_length(split(properties.targetResourceId, \"/\")) - 1])\r\n| where timestamp >= ago(24h) and change_type != \"Update\"\r\n| project format_datetime(timestamp, 'yyyy/MM/dd HH:mm:ss'), tostring(resource), tostring(resource_name), tostring(changed_by), tostring(change_type)\r\n| order by timestamp desc\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 14, "w": 1, "x": 0, "y": 31 } }
 ]
}