{
 "title": "2. Storage Account",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "구독",
    "query": {}
   },
   {
    "name": "StorageAccount",
    "label": "스토리지 계정",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "label": "리소스 그룹",
    "query": {}
   },
   {
    "name": "SubscriptionId",
    "label": "구독 ID",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "데이터 스토리지별 사용량",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Total",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "customNamespace": "microsoft.storage/storageaccounts",
      "dimensionFilters": [],
      "metricName": "UsedCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto",
      "top": "10"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Blob",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "metricName": "BlobCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts/blobservices",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto",
      "top": "10"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Files",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "metricName": "FileCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts/fileservices",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto",
      "top": "10"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Table",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "metricName": "TableCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts/tableservices",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto",
      "top": "10"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Queue",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "metricName": "QueueCapacity",
      "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts/queueservices",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto",
      "top": "10"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "스토리지 계정 리스트",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "resources\r\n| where type =~ \"microsoft.storage/storageaccounts\"\r\n| extend\r\n    performance = tostring(sku.tier),\r\n    redundancy = tostring(sku.name)\r\n| project name, resourceGroup, location, performance, redundancy, kind"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "사용 가능한 용량",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.storage/storageaccounts",
      "dimensionFilters": [],
      "metricName": "Availability",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "재해 복구 지역",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "resources\r\n| where type == \"microsoft.storage/storageaccounts\"\r\n| extend \r\n    primary_location = tostring(properties[\"primaryLocation\"]),\r\n    primary_status = tostring(properties[\"statusOfPrimary\"]),\r\n    second_location = coalesce(tostring(properties[\"secondaryLocation\"]), \"Not Configured\"),\r\n    second_status = coalesce(tostring(properties[\"statusOfSecondary\"]), \"Not Configured\")\r\n| project name, primary_location, primary_status, second_location, second_status\r\n"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "총 트랜잭션 수",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.storage/storageaccounts",
      "dimensionFilters": [],
      "metricName": "Transactions",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "평균 요청 대기 시간",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.storage/storageaccounts",
      "dimensionFilters": [],
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "스토리지 계정 삭제/생성",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 20 },
   "targets": [
    {
     "azureResourceGraph": {
      "query": "resourcechanges\r\n| where properties.targetResourceType contains 'microsoft.storage'\r\n| extend timestamp = todatetime(properties.changeAttributes.timestamp),\r\n    change_type = properties.changeType,\r\n    changed_by = properties.changeAttributes.changedBy,\r\n    resource_name = tostring(split(properties.targetResourceId, \"/\")[array_length(split(properties.targetResourceId, \"/\")) - 1])\r\n| where change_type != \"Update\"\r\n| project format_datetime(timestamp, 'yyyy/MM/dd HH:mm:ss'), tostring(resource_name), tostring(changed_by), tostring(change_type)\r\n| order by timestamp desc"
     },
     "subscriptions": [ "$Subscription" ]
    }
   ]
  },
  {
   "title": "평균 트래픽",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.storage/storageaccounts",
      "dimensionFilters": [],
      "metricName": "Ingress",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.storage/storageaccounts",
      "dimensionFilters": [],
      "metricName": "Egress",
      "metricNamespace": "microsoft.storage/storageaccounts",
      "resources": [
       {
        "metricNamespace": "microsoft.storage/storageaccounts",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$StorageAccount",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  }
 ]
}