{
 "title": "4. VM_Perf",
 "description": "https://github.com/yesoreyeram/grafana-azure-dashboards",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "label": "구독",
    "query": {}
   },
   {
    "name": "SubscriptionId",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "query": {}
   },
   {
    "name": "VM",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "CPU Usage",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto",
      "top": "10"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 7, "x": 3, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; height: 100%; color: #000000; font-size: 13px; flex-direction: column; text-align: center; width: 100%; background-color: white;\">\n    <span style=\"font-weight: 500;\">CPU & Memory</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 7, "x": 10, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; height: 100%; color: #000000; font-size: 13px; flex-direction: column; text-align: center; width: 100%; background-color: white;\">\n    <span style=\"font-weight: 500;\">Network</span>\n</div>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 7, "x": 17, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; justify-content: center; height: 100%; color: #000000; font-size: 13px; flex-direction: column; text-align: center; width: 100%; background-color: white;\">\n    <span style=\"font-weight: 500;\">Disks</span>\n</div>\n"
   }
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "Usage (%)",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Percentage CPU",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{Metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Disk Read / Write Operation(Sec)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Read (OS Disk)",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Read Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Write (OS Disk)",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Write Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Read (Data Disk)",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Data Disk Read Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Write (Data Disk)",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Data Disk Write Operations/Sec",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Network In Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network In Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Network Out Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Available Memory (bytes)",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Available Memory Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto",
      "top": "10"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{Metric}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Network Out Total",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "OS Disk",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "OS Disk Latency",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "Data Disk",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Data Disk Latency",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Read Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Disk Write Bytes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Disk Write Bytes",
      "metricNamespace": "microsoft.compute/virtualmachines",
      "resources": [
       {
        "metricNamespace": "microsoft.compute/virtualmachines",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$VM",
        "subscription": "$SubscriptionId"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  }
 ]
}