{
 "title": "5. Webapp_perf",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Webapp",
    "query": {}
   },
   {
    "name": "ResourceGroup",
    "query": {}
   },
   {
    "name": "SubscriptionId",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "AppConnections",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Requests In Application Queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RequestsInApplicationQueue",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.Web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "microsoft.web/sites",
      "dimensionFilters": [],
      "metricName": "HttpResponseTime",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.Web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Total App Domains",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalAppDomains",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Total Unloaded App Domains",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalAppDomainsUnloaded",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Http server errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http5xx",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "CPU Time / Memory Working Set",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "CpuTime",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "IO Read / Write Operations Per Seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IoReadOperationsPerSecond",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IoWriteOperationsPerSecond",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Http 4xx",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http4xx",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "HTTP 404",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Http404",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Data In",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesReceived",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "Data Out",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BytesSent",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "FileSystem Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 12 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "FileSystemUsage",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  },
  {
   "title": "IO Read / Write Bytes Per Seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IoReadBytesPerSecond",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "IoWriteBytesPerSecond",
      "metricNamespace": "microsoft.web/sites",
      "resources": [
       { "metricNamespace": "microsoft.web/sites", "resourceGroup": "$ResourceGroup", "resourceName": "$Webapp", "subscription": "$SubscriptionId" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$SubscriptionId"
    }
   ]
  }
 ]
}